// components/Menu.vue
<script setup lang="ts">
const showAnimation = ref(false)
const windowWidth = ref(0)
const offset = ref(-120)

onMounted(() => {
  showAnimation.value = true
  windowWidth.value = window.innerWidth
  
  const updateWindowWidth = () => {
    windowWidth.value = window.innerWidth
  }
  
  window.addEventListener('resize', updateWindowWidth)
  
  onUnmounted(() => {
    window.removeEventListener('resize', updateWindowWidth)
  })
})

watch(windowWidth, (newWidth) => {
  if (newWidth < 767) {
    offset.value = 1
  }
})
</script>

<template>
  <div class="flex flex-row items-center justify-center gap-[25px] md:p-2.5 md:gap-2.5 xl:p-5">
    <LinkMenu text="О СТУДИИ" anchor="#studio-section" :offset="offset" :animation="showAnimation" />
    <LinkMenu text="ОБЗОР РАБОТ" anchor="#view-section" :offset="offset" :animation="showAnimation" />
    <LinkMenu text="О МАСТЕРЕ" anchor="#master-section" :offset="offset" :animation="showAnimation" />
    <LinkMenu text="ПРАЙС" anchor="#price-section" :offset="offset" :animation="showAnimation" />
    <LinkMenu text="КАЛЬКУЛЯТОР" anchor="#calculator-section" :offset="offset" :animation="showAnimation" />
    <LinkMenu text="АКЦИИ" anchor="#action-section" :offset="offset" :animation="showAnimation" />
    <LinkMenu text="КОНТАКТЫ" anchor="#contact-section" :offset="offset" :animation="showAnimation" />
    <button class="max-w-[200px] bg-inherit animate-scale-button text-text text-sm md:text-base lg:text-lg border border-text rounded-2xl p-[5px] w-[150px] transition-all duration-300 z-[1] hover:bg-text-additional hover:text-main md:w-[125px] md:ml-5 xl:ml-5">
      <a href="https://vk.com/keratin_botox_plessvk" target="_blank" rel="noreferrer">
        Группа в VK
      </a>
    </button>
  </div>
</template>

// src/component/Menu/Menu.tsx
import type { FC } from 'react';
import { useState, useEffect } from 'react';
import LinkMenu from '../LinkMenu/LinkMenu';
interface MenuProps {}

const Menu: FC<MenuProps> = () => {
  const [showAnimation, setShowAnimation] = useState(false);
  const [windowWidth, setWindowWidth] = useState(window.innerWidth);
  const [offset, setOffset] = useState(-120);
  useEffect(() => {
    setShowAnimation(true);
  }, []);

  useEffect(() => {
    const updateWindowWidth = () => {
      setWindowWidth(window.innerWidth);
    };
    // Добавляем слушатель изменения размера окна
    window.addEventListener('resize', updateWindowWidth);
    // Вызываем функцию для первоначальной установки ширины окна
    updateWindowWidth();
    // Очищаем слушатель при размонтировании компонента
    return () => {
      window.removeEventListener('resize', updateWindowWidth);
    };
  }, []); // Пустая зависимость, так как мы не зависимы от windowWidth

  useEffect(() => {
    if (windowWidth < 767) {
      setOffset(1);
    }
  }, [windowWidth]);
  return (
    <div className='menu'>
      <LinkMenu text='О СТУДИИ' anchor='#studio-section' offset={offset} animation={showAnimation}></LinkMenu>
      <LinkMenu text='ОБЗОР РАБОТ' anchor='#view-section' offset={offset} animation={showAnimation}></LinkMenu>
      <LinkMenu text='О МАСТЕРЕ' anchor='#master-section' offset={offset} animation={showAnimation}></LinkMenu>
      <LinkMenu text='ПРАЙС' anchor='#price-section' offset={offset} animation={showAnimation}></LinkMenu>
      <LinkMenu text='КАЛЬКУЛЯТОР' anchor='#calculator-section' offset={offset} animation={showAnimation}></LinkMenu>
      <LinkMenu text='АКЦИИ' anchor='#action-section' offset={offset} animation={showAnimation}></LinkMenu>
      <LinkMenu text='КОНТАКТЫ' anchor='#contact-section' offset={offset} animation={showAnimation}></LinkMenu>
      <button className='map-vk-button fixed-button'>
        <a href='https://vk.com/keratin_botox_plessvk' target='_blank' rel='noreferrer'>
          Группа в VK
        </a>
      </button>
    </div>
  );
};

export default Menu;
